# General Settings
exp_name: Torch                                  # Experiment name
seed: 0                                          # Random seed for reproducibility
numpy_seed : 0                                   # Numpy seed 
cuda: true                                       # Whether to use GPU (CUDA)
batch_size: 4                                    # Batch size for training
num_steps: 15000                                 # Total training steps
pretrained: false                                # Use a pretrained model
checkpoints_path: ./checkpoints/                 # Path to save checkpoints
logs_path: ./logs/                               # Path for logging
saved_models: ./models/                          # Path for saving trained models
train_path: /kaggle/input/mirflickr-1m/          # Path to training data

# Loss Function Parameters
l2_loss_scale: 1                                 # Maximum scale for L2 loss
l2_loss_ramp: 15000                              # Ramp-up steps for L2 loss
l2_edge_gain: 10                                 # Edge gain for L2 loss
l2_edge_ramp: 10000                              # Ramp-up steps for edge L2 loss
l2_edge_delay: 80000                             # Delay before L2 edge ramp starts

lpips_loss_scale: 0.75                           # Maximum scale for LPIPS loss
lpips_loss_ramp: 7500                            # Ramp-up steps for LPIPS loss

secret_loss_scale: 3                             # Maximum scale for secret loss
secret_loss_ramp: 1                              # Ramp-up steps for secret loss

G_loss_scale: 0.5                                # Maximum scale for generator loss
G_loss_ramp: 15000                               # Ramp-up steps for generator loss

min_loss: 1000                                   # Minimum loss threshold
min_secret_loss: 1000                            # Minimum secret loss threshold

# Contrast Adjustment
contrast_low: 0.5                                # Minimum contrast scale
contrast_high: 1.5                               # Maximum contrast scale
contrast_ramp: 1000                              # Ramp-up steps for contrast adjustments

# HSV (Hue, Saturation, Value) Scaling
hsv_h_scale: 0.5                                   # Hue scale factor
hsv_s_scale: 1                                   # Saturation scale factor
hsv_v_scale: 1                                   # Value (brightness) scale factor

# Random Transformations
rnd_bri: 0.3                                     # Random brightness adjustment range
rnd_bri_ramp: 1000                               # Ramp-up steps for brightness adjustment
rnd_hue: 0.1                                     # Random hue adjustment range
rnd_hue_ramp: 1000                               # Ramp-up steps for hue adjustment
rnd_sat: 1.0                                     # Random saturation adjustment range
rnd_sat_ramp: 1000                               # Ramp-up steps for saturation adjustment
rnd_noise: 0.02                                  # Random noise intensity
rnd_noise_ramp: 1000                             # Ramp-up steps for noise intensity
rnd_trans: 0.1                                   # Random transformation range
rnd_trans_ramp: 10000                            # Ramp-up steps for transformation adjustments

# JPEG Compression
jpeg_quality: 50                                 # JPEG quality factor
jpeg_quality_ramp: 1000                          # Ramp-up steps for JPEG quality
no_jpeg: true                                    # Disable JPEG compression during training

# GAN and UNet Settings
no_gan: true                                      # Disable GAN loss
KAN: false                                        # Enable/disable KAN
UNet: true                                        # Enable/disable UNet

# Color Space and Borders
color_space: RGB                                  # Color space (e.g., RGB, YUV)
borders: no_edge                                  # Border processing type (e.g., no_edge, edge)

# Learning Rate
lr: 0.0001                                        # Learning rate

# Secret Embedding
secret_size: 100                                  # Size of the secret embedding

# YUV Scaling
y_scale: 1                                        # Y-channel scale in YUV color space
u_scale: 100                                      # U-channel scale in YUV color space
v_scale: 100                                      # V-channel scale in YUV color space

# Steps Configuration
no_im_loss_steps: 1750                            # Steps before image loss is enabled
